backend = "glx";
vsync = true;

shadow = false;

shadow-exclude = [
  "QTILE_INTERNAL = 1",
  "class_g = 'Dunst'"
];

blur-background-exclude = [
  "QTILE_INTERNAL = 1"
];

fade-exclude = [
  "QTILE_INTERNAL = 1"
];