#!/usr/bin/env bash
# Extract nmap Information:
ports="$(cat $1 | grep -oP '\d{1,5}/open' | awk '{print $1}' FS='/' | xargs | tr ' ' ',')"
ipAddress="$(cat $1 | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | sort -u | head -n 1)"
echo -e "\n [*] Extracting information... \n" >./extractPorts.tmp
echo -e "\t [*] IP Address: $ipAddress" >>./extractPorts.tmp
echo -e "\t [*] Open ports: $ports \n" >>./extractPorts.tmp
echo $ports | tr -d '\n' | xclip -sel clip
echo -e "[*] Ports copied to clipboard \n" >>./extractPorts.tmp
batcat -fl java ./extractPorts.tmp
rm -f ./extractPorts.tmp
