[font]
size = 18.0

[window]
option_as_alt = "Both"
opacity = 0.3
startup_mode = "Maximized"

[cursor]
thickness = 0.1
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font.normal]
family = "Cascadia Code NF"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[window.padding]
x = 10
y = 10

[cursor.style]
shape = "Beam"
blinking = "Always"

[colors.primary]
background = "#0f101a"
foreground = "#c5c9de"

[colors.normal]
black = "#181a29"
red = "#F07178"
green = "#cdea9f"
yellow = "#ffd47e"
blue = "#93bbff"
magenta = "#d3a7ee"
cyan = "#98e4ff"
white = "#bfd5de"

[colors.bright]
black = "#282a40"
red = "#eb7f84"
green = "#e0ffad"
yellow = "#ffee7e"
blue = "#a3c5ff"
magenta = "#d6afed"
cyan = "#98fffd"
white = "#d1e5ed"
