[font]
size = 14.0

[window]
option_as_alt = "Both"
opacity = 0.7
startup_mode = "Maximized"

[cursor]
thickness = 0.0
unfocused_hollow = true

[font.normal]
family = "Cascadia Code NF"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[window.padding]
x = 10
y = 10

[cursor.style]
shape = "Beam"
blinking = "Always"

# [colors.primary]
# background = "#24283b"
# foreground = "#a9b1d6"

# [colors.normal]
# black = "#32344a"
# red = "#f7768e"
# green = "#9ece6a"
# yellow = "#e0af68"
# blue = "#7aa2f7"
# magenta = "#ad8ee6"
# cyan = "#449dab"
# white = "#9699a8"

# [colors.bright]
# black = "#444b6a"
# red = "#ff7a93"
# green = "#b9f27c"
# yellow = "#ff9e64"
# blue = "#7da6ff"
# magenta = "#bb9af7"
# cyan = "#0db9d7"
# white = "#acb0d0"

# ...

# Adaptation of colors from WezTerm to Alacritty in TOML format

# [[colors.indexed_colors]]
# color = "#ffa066"  # Additional color
# index = 16

[[colors.indexed_colors]]
color = "#ff5d62"  # Additional color
index = 17

[colors.bright]
black = "#727169"   # Bright ANSI Black
blue = "#7fb4ca"    # Bright ANSI Blue
cyan = "#7aa89f"    # Bright ANSI Cyan
green = "#98bb6c"   # Bright ANSI Green
magenta = "#938aa9" # Bright ANSI Magenta
red = "#e82424"     # Bright ANSI Red
white = "#dcd7ba"   # Bright ANSI White
yellow = "#e6c384"  # Bright ANSI Yellow

[colors.cursor]
cursor = "#c8c093"  # Cursor color
text = "#c8c093"    # Cursor text color

[colors.normal]
black = "#090618"   # ANSI Black
blue = "#7e9cd8"    # ANSI Blue
cyan = "#6a9589"    # ANSI Cyan
green = "#76946a"   # ANSI Green
magenta = "#957fb8" # ANSI Magenta
red = "#c34043"     # ANSI Red
white = "#c8c093"   # ANSI White
yellow = "#c0a36e"  # ANSI Yellow

[colors.primary]
background = "#181616"  # Background color
foreground = "#dcd7ba"  # Foreground color

[colors.selection]
background = "#2d4f67"  # Selection background color
text = "#c8c093"        # Selection text color

[env]
TERM = "xterm-256color"

# Uncomment for Windows
# [shell]
# program = "wsl.exe"
# args = ["--cd","~"]

